HN 002 : Add See Comments
AsminBudha/hacker-news pull request #4
Opened 2019-01-23 04:35 UTC by AsminBudha

1. Add single post when click to post.
2. Add comments and sub comments.

2019-01-23 07:16 UTC, badyakarprabin requested changes

2019-01-23 07:16 UTC, badyakarprabin commented on src/AppRouter.js
> +import AppConstants from './constants/common';
``` import * as appConstants from './constants/common'; ```

2019-01-23 07:16 UTC, badyakarprabin commented on src/AppRouter.js
> +        <div>
Why do we need div here?

2019-01-23 07:16 UTC, badyakarprabin commented on src/components/Comments.js
> +const Comments = (props) => {
``` 
const Comments = ({data = [] }) => {

  const items = data
    .map((id) => {
      return <li key={id}><SingleComment id={id} /></li>;
    });
```

No need to use const kids.

2019-01-23 07:16 UTC, badyakarprabin commented on src/components/Header.js
> +const Header = () => <h1>Hacker News</h1>;
``` <h1> {appContants.HEADER} </h1> ```

You might have used Hacker News in multiple places. What if someone asked you to change your application name form Hacker New to Hacker Post ?

2019-01-23 07:16 UTC, badyakarprabin commented on src/components/NewsItem.js
> +    Http
``` http.get ```

2019-01-23 07:16 UTC, badyakarprabin commented on src/components/NewsItem.js
> +
Extra line

2019-01-23 07:16 UTC, badyakarprabin commented on src/components/NewsItem.js
> +    const { data } = this.state;
``` const {data: {title, by, time}} ```

2019-01-23 07:16 UTC, badyakarprabin commented on src/components/NewsItem.js
> +          <span onClick={() => window.location.href = data.url}> Read More</span>
``` onClick={this.onChangeLocation} ```

2019-01-23 07:16 UTC, badyakarprabin commented on src/components/NewsItem.js
> +              pathname: `${AppConstants.API_ITEM}/:${data.id}`,
.

2019-01-23 07:16 UTC, badyakarprabin commented on src/components/NewsList.js
> +  updatePage = (by) => {
What is meaning of by here???

2019-01-23 07:16 UTC, badyakarprabin commented on src/components/NewsList.js
> +    const dataIds = Http.get(path);
.

2019-01-23 07:16 UTC, badyakarprabin commented on src/components/NewsList.js
> +          Next
``` appConstants.NEXT```

2019-01-23 07:16 UTC, badyakarprabin commented on src/components/NotFound.js
> +export default notFound;
Component name always starts with capital letter.
``` 
const NotFound = () ....

export default NotFound 
```

2019-01-23 07:16 UTC, badyakarprabin commented on src/components/SingleComment.js
> +import Http from '../services/http';
Only component starts with capital letter.

2019-01-23 07:16 UTC, badyakarprabin commented on src/components/SingleComment.js
> +import AppConstants from '../constants/common';
same

2019-01-23 07:16 UTC, badyakarprabin commented on src/components/SingleComment.js
> +      data: null,
null or []?

2019-01-23 07:16 UTC, badyakarprabin commented on src/components/SinglePost.js
> +      <h2>{data.title}</h2>
yesma k garna milxa ho????

2019-01-23 07:16 UTC, badyakarprabin commented on src/components/Tabs.js
> +        <li className="tab"><Link to={Common.API_TOP_STORIES} className='active'>Top Stories</Link></li>
Top stories shoud be imported from constants files

2019-01-23 07:16 UTC, badyakarprabin commented on src/constants/common.js
> +const TOP_STORIES = 0;
yo gare ni hunxa or
```
export const NEW_STORIES = 1;
export cont BEST_STORIES = 2;

import * as appConstants from 'common';
```

2019-01-23 11:19 UTC, AsminBudha commented on src/AppRouter.js
> +        <div>
Router needs to have single child.

2019-01-24 08:12 UTC, AsminBudha commented on src/components/SingleComment.js
> +      data: null,
data store single object not an array.

2019-01-28 03:55 UTC, merged